version: '3.3'
services:

  nginx:
    image: councilmatic-nginx
    build:
      context: .
      dockerfile: docker/nginx-dockerfile
    ports:
      - "4143:80"
    links:
      - application
    volumes:
      - ./configs/nginx.conf:/etc/nginx/conf.d/chicago.conf
    depends_on:
      - application

  application:
    image: chicouncilmatic_application
    build:
      context: .
      dockerfile: docker/application-dockerfile
    container_name: chicouncilmatic_application
    command: sh -c 'gunicorn -b 0.0.0.0:5000 councilmatic.wsgi:application'
    expose:
      - "5000"
    links:
      - database
    depends_on:
      - database
    secrets:
      - settings_deployment.py
    environment:
      APPLICATION_CONFIG: /run/secrets/settings_deployment.py

  worker:
    image: chicouncilmatic_application
    build:
      context: .
      dockerfile: docker/application-dockerfile
    depends_on:
      - database
      - redis
    container_name: chicouncilmatic_worker
    command: sh -c 'python manage.py rqworker default'
    links:
      - database
    secrets:
      - settings_deployment.py
    environment:
      APPLICATION_CONFIG: /run/secrets/settings_deployment.py

  cron:
    build:
      context: .
      dockerfile: docker/cron-dockerfile
    container_name: chicouncilmatic_cron
    command: sh -c 'python cron.py'
    links:
      - database
      - solr
    depends_on:
      - database
      - solr
    secrets:
      - settings_deployment.py
    environment:
      APPLICATION_CONFIG: /run/secrets/settings_deployment.py
      DJANGO_SETTINGS_MODULE: councilmatic.settings

  redis:
    image: redis:latest
    container_name: chicouncilmatic_redis
    expose:
      - "6379"

  database:
    build:
      context: docker
      dockerfile: database-dockerfile
    container_name: chicouncilmatic_database
    expose:
      - "5432"
    ports:
      - "5433:5432"
    volumes:
      - /data/chicago:/var/lib/postgresql/data

  solr:
    image: solr:7
    container_name: chicouncilmatic_solr
    volumes:
      - ./solr_configs:/chicago_configs
    command: sh -c 'solr-create -c chicago -d /chicago_configs'
    expose:
      - "8983"
    environment:
      SOLR_LOG_LEVEL: ERROR

secrets:
  settings_deployment.py:
    file: ./councilmatic/settings_deployment.py
